# Generated by Django 4.1 on 2023-09-12 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quiz',
        ),
        migrations.AlterField(
            model_name='user_scores',
            name='user_id',
            field=models.ForeignKey(db_column='group_code', default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='backendapp.user_details'),
        ),
    ]
