# Generated by Django 4.1 on 2023-09-12 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0002_delete_quiz_alter_user_scores_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_scores',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='User_Details',
        ),
        migrations.DeleteModel(
            name='User_Scores',
        ),
    ]
